# Generated by Django 4.1.4 on 2022-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edibles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA5L8IbQ846lWwlpYLaguWNOP3mSSE0klyig&usqp=CAU",
                max_length=500,
            ),
        ),
    ]
